import Header from '@/components/Header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/global.scss'
import StyledComponentsRegistry from '@/providers/AntdRegistry'
import theme from '@/antDesign/themeConfig'
import {ConfigProvider} from 'antd'
import ReduxProvider from '@/providers/reduxProvider'
import ReactQueryProvider from '@/providers/reactQueryProvider'
import Script from 'next/script'


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      
      <body className={inter.className}>
        <ConfigProvider theme={theme} >
        <StyledComponentsRegistry>
          <ReduxProvider>
            <ReactQueryProvider>
        <div className="container">
        <Header/>
          {children}
        </div>   
        </ReactQueryProvider>
        </ReduxProvider>
       
          </StyledComponentsRegistry>
        </ConfigProvider>
        
        </body>
    </html>
  )
}
