import Header from '@/components/Header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/global.scss'
import StyledComponentsRegistry from '@/antDesign/AntdRegistry'
import theme from '@/antDesign/themeConfig'
import {ConfigProvider} from 'antd'
import ReduxProvider from '@/redux_toolkit/reduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <ConfigProvider theme={theme} >
        <StyledComponentsRegistry>
          <ReduxProvider>
        <div className="container">
        <Header/>
          {children}
        </div>
          </ReduxProvider>
          </StyledComponentsRegistry>
        </ConfigProvider>
        </body>
    </html>
  )
}
